import ConnesLean.Common.Notation
import ConnesLean.Stage1.MultiplicativeHaar
import ConnesLean.Stage1.DilationOperator
import ConnesLean.Stage1.Convolution
import ConnesLean.Stage1.ConvolutionInnerProduct
import ConnesLean.Stage1.UnitaryIdentity
